; PlatformIO Project Configuration File
;
; Tests board_build.ulp_dir with a non-default ULP source directory.
; This is a copy of espidf-ulp-lp with ulp/ renamed to lp_core/.

[env:esp32-c6]
platform = espressif32
framework = espidf
board = esp32-c6-devkitc-1
board_build.ulp_dir = lp_core
